--Create a table

  CREATE TABLE ELEMENTS(ELEMENT VARCHAR(10),SEQUENCE int);

--insert the values into table

INSERT INTO ELEMENTS VALUES ('A', '1'); 
INSERT INTO ELEMENTS VALUES ('A', '2'); 
INSERT INTO ELEMENTS VALUES ('A', '3'); 
INSERT INTO ELEMENTS VALUES ('A', '5'); 
INSERT INTO ELEMENTS VALUES ('A', '6'); 
INSERT INTO ELEMENTS VALUES ('A', '8'); 
INSERT INTO ELEMENTS VALUES ('A', '9'); 
INSERT INTO ELEMENTS VALUES ('B', '11'); 
INSERT INTO ELEMENTS VALUES ('C', '13'); 
INSERT INTO ELEMENTS VALUES ('C', '14'); 
INSERT INTO ELEMENTS VALUES ('C', '15');


--SQL logic

SELECT ELEMENT,MAX(SEQUENCE) AS MAX_SEQ,MIN(SEQUENCE) AS MIN_SEQ FROM ELEMENTS GROUP BY ELEMENT ORDER BY ELEMENT ASC;

o/p:
 
ELEMENT
MAX_SEQ
MIN_SEQ
A
9
1
B
11
11
C
15
13
